'use client';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Classroom, DEFAULT_BADGE_COLOR, LEAGUES, LEAGUE_INFO, League, Season, Standing, initialAssignment, currentSeason, standings, stage, scheduleDefaults, addDays, membersNow, movementPreview, compareScore, activeMatches } from '@/lib/league';
import Icon from './icon';
import { Empty, LeagueChip, timeLabel, dateLabel } from './ui';
import { MedalArt } from './medal';
import type { Mutate } from './league-app';
type Props = { state: Classroom; today: string; busy: boolean; mutate: Mutate; notify: (message: string, error?: boolean) => void; publicMode: () => void; disconnect: () => Promise<void> };
const tabs = [{ id: 'overview', name: '운영 현황', icon: 'home' }, { id: 'placement', name: '학생·배치', icon: 'users' }, { id: 'season', name: '시즌·승강', icon: 'trophy' }, { id: 'matches', name: '경기 정정', icon: 'swords' }, { id: 'badges', name: '커스텀 훈장', icon: 'medal' }, { id: 'settings', name: '활동 설정', icon: 'settings' }];
export default function Admin(props: Props) {
  const [tab, setTab] = useState('overview');
  const { state, today, busy, mutate, notify } = props;
  const current = stage(state, today), season = currentSeason(state);
  const operate = async (action: string, payload: Record<string, unknown>) => { const success = await mutate(action, payload); if (success) notify('저장했습니다.'); return success; };
  return <><div className="teacher-banner"><span><Icon name="unlock" size={20} /><strong>교사 관리 모드</strong>작업을 마치면 공용 모드로 전환해 주세요.</span><button className="btn secondary small" onClick={props.publicMode}><Icon name="lock" size={17} />공용 모드로</button></div><div className="admin-tabs" role="navigation" aria-label="교사 메뉴">{tabs.map(t => <button key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}><Icon name={t.icon} size={18} />{t.name}</button>)}</div>
    {tab === 'overview' && <><div className="admin-summary"><div className="panel"><span className="eyebrow">현재 운영</span><h2>{current.title}</h2><p>{current.message}</p><div className="admin-numbers"><div><strong>{state.students.length}</strong><span>등록 학생</span></div><div><strong>{state.matches.filter(m => !m.voided).length}</strong><span>전체 경기</span></div><div><strong>{state.seasons.length}</strong><span>시즌</span></div></div></div><div className="panel"><h2>다음 운영 단계</h2><div className="operation-list">{[{ done: true, title: '학급과 학생 명단 준비', desc: state.name, tab: 'placement' }, { done: state.placed, title: '최초 리그 배정', desc: '배치전 기록을 보고 교사가 확정', tab: 'placement' }, { done: !!season, title: '시즌 일정 설정', desc: '리그전과 승급 기간 1~3회', tab: 'season' }].map(item => <button key={item.title} onClick={() => setTab(item.tab)}><span className={`operation-check ${item.done ? 'done' : ''}`}><Icon name={item.done ? 'check' : 'arrow'} size={18} /></span><div><strong>{item.title}</strong><small>{item.desc}</small></div><Icon name="arrow" size={16} /></button>)}</div></div></div><div className="panel teacher-instructions"><h2>공용 태블릿으로 운영하기</h2><div><p><strong>01</strong>교사가 명단·리그·일정을 준비합니다.</p><p><strong>02</strong>공용 모드로 전환하고 태블릿을 열어 둡니다.</p><p><strong>03</strong>대결한 두 학생이 함께 이름과 승자를 선택합니다.</p><p><strong>04</strong>오입력은 교사 관리에서 정정합니다.</p></div></div></>}
    {tab === 'placement' && <Placement state={state} busy={busy} mutate={operate} />}
    {tab === 'season' && <SeasonControl {...props} mutate={operate} />}
    {tab === 'matches' && <MatchManagement state={state} busy={busy} mutate={operate} />}
    {tab === 'badges' && <Praise state={state} busy={busy} mutate={operate} />}
    {tab === 'settings' && <Settings {...props} mutate={operate} />}
  </>;
}

function Placement({ state, busy, mutate }: { state: Classroom; busy: boolean; mutate: Mutate }) {
  const [members, setMembers] = useState<Record<string, League>>(() => initialAssignment(state.students, state.matches)), [checked, setChecked] = useState(false);
  const [names, setNames] = useState(state.students.map(s => s.name).join('\n')), [limit, setLimit] = useState(state.placementLimit);
  const [placementStart, setPlacementStart] = useState(state.placement?.start || ''), [placementEnd, setPlacementEnd] = useState(state.placement?.end || '');
  const rows = standings(state), canEditRoster = !state.placed && !state.matches.some(m => !m.voided);
  const rosterKey = state.students.map(s => s.id).join(','), resultKey = state.matches.map(m => `${m.id}:${m.winner}:${m.voided}`).join(',');
  useEffect(() => { if (!state.placed) { setMembers(initialAssignment(state.students, state.matches)); setChecked(false); } }, [rosterKey, resultKey, state.placed]);
  const shownMembers = state.placed ? membersNow(state) : members;
  return <><div className="section-head"><div><h2>{state.placed ? '학생 명단과 현재 소속' : '배치전을 보고 첫 리그를 정해요'}</h2><p className="muted">배치전은 학급 최초 한 번만 운영합니다. 결석과 동점은 교사가 확인해 주세요.</p></div><span className="pill subtle">{state.placed ? '배치 완료' : '배치전 진행 중'}</span></div><div className="league-counts">{LEAGUES.map(l => <div key={l}><LeagueChip league={l} /><strong>{Object.values(shownMembers).filter(v => v === l).length}명</strong></div>)}</div><section className="panel"><div className="table-scroll"><table><thead><tr><th>번호</th><th>학생</th><th>배치전 승 / 패</th><th>배치 경기</th><th>{state.placed ? '현재 리그' : '첫 리그 배정'}</th></tr></thead><tbody>{state.students.map(s => { const row = rows.find(r => r.id === s.id)!; return <tr key={s.id}><td>{s.number}</td><td><span className="table-person"><strong>{s.name}</strong></span></td><td>{row.wins} / {row.losses}</td><td>{activeMatches(state, 'placement').filter(m => m.a === s.id || m.b === s.id).length} / {state.placementLimit}</td><td>{state.placed ? <LeagueChip league={shownMembers[s.id]} /> : <select aria-label={`${s.name} 첫 리그`} value={members[s.id]} onChange={e => { setMembers({ ...members, [s.id]: e.target.value as League }); setChecked(false); }}>{LEAGUES.map(l => <option key={l} value={l}>{LEAGUE_INFO[l].name}</option>)}</select>}</td></tr>; })}</tbody></table></div>{!state.placed && <div className="placement-confirm"><label className="check-field"><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} />동점·결석 학생과 각 리그 인원을 확인했습니다.</label><button className="btn primary" disabled={busy || !checked} onClick={() => mutate('place', { members })}>최초 리그 배정 확정<Icon name="check" size={18} /></button></div>}</section>
    {!state.placed && <div className="admin-two-columns"><div className="panel"><form onSubmit={e => { e.preventDefault(); mutate('placementLimit', { limit }); }}><h3>배치전 경기 수</h3><label className="field">학생당 경기 기회<input type="number" value={limit} min={1} max={state.students.length - 1} onChange={e => setLimit(Number(e.target.value))} required /></label><button className="btn secondary" disabled={busy}>경기 수 저장</button></form>{canEditRoster && <form className="placement-date-form" onSubmit={e => { e.preventDefault(); mutate('placementDates', { start: placementStart, end: placementEnd }); }}><h3>배치전 일정 · 기본 2일</h3><div className="form-grid two"><label className="field">시작일<input type="date" value={placementStart} onChange={e => setPlacementStart(e.target.value)} required /></label><label className="field">종료일<input type="date" value={placementEnd} onChange={e => setPlacementEnd(e.target.value)} required /></label></div><button className="btn secondary" disabled={busy}>배치전 날짜 저장</button></form>}</div>{canEditRoster && <form className="panel" onSubmit={e => { e.preventDefault(); mutate('students', { names: names.split('\n').map(n => n.trim()).filter(Boolean) }); }}><h3>학생 명단 수정</h3><p className="muted">첫 경기를 기록하기 전까지만 수정할 수 있습니다.</p><label className="field">한 줄에 한 명<textarea value={names} onChange={e => setNames(e.target.value)} rows={6} required /></label><button className="btn secondary" disabled={busy}>명단 저장</button></form>}</div>}
  </>;
}

function SeasonControl(props: Props) {
  const { state, today } = props, season = currentSeason(state), [editing, setEditing] = useState(false);
  if (!state.placed) return <section className="panel"><Empty icon="trophy" title="최초 리그 배정이 필요합니다">학생·배치 메뉴에서 첫 리그를 확정한 뒤 시즌을 설정해 주세요.</Empty></section>;
  if (!season || season.completed) return <><div className="section-head"><div><h2>{season ? '다음 시즌 준비' : '첫 시즌 시작하기'}</h2><p className="muted">{season ? '지난 시즌의 확정된 다음 소속으로 시작합니다. 배치전은 반복하지 않습니다.' : '승급 기간 날짜와 경기 수를 수업 일정에 맞춰 정해 주세요.'}</p></div></div><SeasonForm state={state} today={today} busy={props.busy} mutate={props.mutate} notify={props.notify} /></>;
  return <><div className="section-head"><div><h2>{season.name}</h2><p className="muted">{season.start} — {season.end} · 승급 기간 {season.rounds.length}회</p></div><button className="btn secondary" onClick={() => setEditing(!editing)}><Icon name="edit" size={17} />{editing ? '일정 수정 닫기' : '일정 수정'}</button></div>{editing && <SeasonForm key={season.id} state={state} today={today} season={season} busy={props.busy} mutate={async (a, p) => { const ok = await props.mutate(a, p); if (ok) setEditing(false); return ok; }} notify={props.notify} />}<div className="panel"><div className="section-head"><h3>시즌 일정</h3><span className="pill subtle">날짜에 따라 자동 전환</span></div><div className="table-scroll"><table><thead><tr><th>구간</th><th>리그전</th><th>경기 수</th><th>승급 기간</th><th>경기 수</th><th>상태</th></tr></thead><tbody>{season.rounds.map(r => <tr key={r.id}><td>{r.index}차</td><td>{dateLabel(r.league.start)} — {dateLabel(r.league.end)}</td><td>{r.league.limit}회</td><td>{dateLabel(r.promotion.start)} — {dateLabel(r.promotion.end)}</td><td>{r.promotion.limit}회</td><td><span className="pill subtle">{r.closed ? '마감 완료' : season.rounds.find(x => !x.closed)?.id === r.id ? '현재 구간' : '예정'}</span></td></tr>)}</tbody></table></div></div><Fixtures {...props} /><Closing {...props} /></>;
}
function SeasonForm({ state, today, season, busy, mutate, notify }: { state: Classroom; today: string; season?: Season; busy: boolean; mutate: Mutate; notify: Props['notify'] }) {
  const previous = currentSeason(state), initialStart = season?.start || (previous && previous.end >= today ? addDays(previous.end, 1) : today);
  const members = previous?.completed ? previous.nextMembers! : state.initialMembers;
  const counts = LEAGUES.map(l => Object.values(members).filter(v => v === l).length);
  const defaultLimit = Math.min(2, Math.min(...counts) - 1);
  const [name, setName] = useState(season?.name || `우리 반 시즌 ${state.seasons.length + 1}`), [start, setStart] = useState(initialStart), [end, setEnd] = useState(season?.end || addDays(initialStart, 27)), [count, setCount] = useState(season?.rounds.length || 2);
  const [rounds, setRounds] = useState(() => season?.rounds.map(r => ({ league: { start: r.league.start, end: r.league.end, limit: r.league.limit }, promotion: { start: r.promotion.start, end: r.promotion.end, limit: r.promotion.limit } })) || scheduleDefaults(initialStart, addDays(initialStart, 27), 2, defaultLimit));
  const [exchanges, setExchanges] = useState<[number, number]>(season?.exchanges || [Math.min(2, counts[0], Math.floor(counts[1] / 2)), Math.min(2, counts[2], Math.floor(counts[1] / 2))]);
  function propose() { try { setRounds(scheduleDefaults(start, end, count, defaultLimit)); } catch (e) { notify((e as Error).message, true); } }
  function update(i: number, kind: 'league' | 'promotion', field: string, value: string | number) { setRounds(old => old.map((r, index) => index === i ? { ...r, [kind]: { ...r[kind], [field]: value } } : r)); }
  async function submit(e: FormEvent) {
    e.preventDefault();
    if (count !== rounds.length) { notify('승급 기간 횟수를 바꾼 뒤 일정 제안을 눌러 주세요.', true); return; }
    await mutate(season ? 'updateSeason' : 'season', { name, start, end, exchanges, rounds });
  }
  return <form className="panel season-form" onSubmit={submit}><h3>{season ? '일정과 경기 수 수정' : '시즌 설정'}</h3>{season && <div className="notice">이미 경기 기록이 있는 단계는 날짜·경기 수를 변경할 수 없습니다. 마감한 구간과 적용한 승강도 유지됩니다.</div>}<div className="form-grid three"><label className="field">시즌 이름<input value={name} onChange={e => setName(e.target.value)} required maxLength={50} /></label><label className="field">시작일<input type="date" value={start} onChange={e => setStart(e.target.value)} required /></label><label className="field">종료일<input type="date" value={end} onChange={e => setEnd(e.target.value)} required /></label></div><div className="schedule-propose"><label className="field">승급 기간 횟수<select value={count} onChange={e => setCount(Number(e.target.value))}>{[1, 2, 3].map(n => <option value={n} key={n}>{n}회</option>)}</select></label><button type="button" className="btn secondary" onClick={propose}><Icon name="calendar" size={18} />일정 제안</button><p>시즌을 같은 길이로 나누고,<br />각 구간 마지막 2일을 승급 기간으로 제안합니다.</p></div><div className="round-forms">{rounds.map((r, i) => <div className="round-form" key={i}><div className="round-form-label">{i + 1}차 구간</div>{(['league', 'promotion'] as const).map(kind => <div className="round-form-phase" key={kind}><strong>{kind === 'league' ? '리그전 · 승리 +10 RP' : '승급 기간 · 승리 +15 RP'}</strong><div className="form-grid three"><label className="field">시작일<input type="date" required value={r[kind].start} onChange={e => update(i, kind, 'start', e.target.value)} /></label><label className="field">종료일<input type="date" required value={r[kind].end} onChange={e => update(i, kind, 'end', e.target.value)} /></label><label className="field">{kind === 'league' ? '학생당 최대 경기 수' : '학생당 배정 경기 수'}<input type="number" required min={1} max={Math.min(...counts) - 1} value={r[kind].limit} onChange={e => update(i, kind, 'limit', Number(e.target.value))} /></label></div></div>)}</div>)}</div><div className="form-grid two"><label className="field">루키 ↔ 챌린저 교환 인원<input type="number" required min={0} value={exchanges[0]} onChange={e => setExchanges([Number(e.target.value), exchanges[1]])} /></label><label className="field">챌린저 ↔ 챔피언 교환 인원<input type="number" required min={0} value={exchanges[1]} onChange={e => setExchanges([exchanges[0], Number(e.target.value)])} /></label></div><div className="notice">리그전은 학생당 최대 횟수까지 기록할 수 있습니다. 승급전 횟수는 별도로 계산하며 모든 학생에게 같은 수로 대진을 배정합니다. 승급전은 홀수 인원의 리그에 홀수 경기 수를 설정하면 저장할 수 없습니다. 실제 수업일에 경기를 마칠 수 있는지도 확인해 주세요.</div><button className="btn primary" disabled={busy}>{busy ? '저장 중…' : season ? '시즌 설정 저장' : '시즌 만들기'}<Icon name="arrow" size={18} /></button></form>;
}
function Fixtures({ state, busy, mutate }: Props) {
  const round = currentSeason(state)!.rounds.find(r => !r.closed)!, [first, setFirst] = useState(''), [second, setSecond] = useState('');
  const matches = activeMatches(state, round.promotion.id), name = (id: string) => state.students.find(s => s.id === id)!.name;
  const firstFixture = round.fixtures.find(f => f.id === first);
  return <section className="panel fixtures-panel"><div className="section-head"><div><h3>{round.index}차 승급 기간 대진</h3><p className="muted">같은 리그 안에서 학생마다 {round.promotion.limit}경기씩, 중복 없이 배정했습니다.</p></div><span className="pill subtle">{matches.length}/{round.fixtures.length} 완료</span></div><div className="fixture-columns">{LEAGUES.map(l => <div key={l}><LeagueChip league={l} />{round.fixtures.filter(f => f.league === l).map(f => { const done = matches.some(m => [m.a, m.b].includes(f.a) && [m.a, m.b].includes(f.b)); return <div className={`fixture ${done ? 'done' : ''}`} key={f.id}><span>{name(f.a)}<small> vs </small>{name(f.b)}</span><Icon name={done ? 'check' : 'swords'} size={16} /></div>; })}</div>)}</div>{!matches.length && <div className="fixture-edit"><h4>대진 상대 바꾸기</h4><p className="muted">같은 리그의 두 경기를 선택하면 두 번째 학생을 서로 교환합니다. 경기 수·중복 규칙이 유지되는 경우에만 변경됩니다.</p><div className="form-grid two"><label className="field">첫 번째 대진<select value={first} onChange={e => { setFirst(e.target.value); setSecond(''); }}><option value="">대진 선택</option>{round.fixtures.map(f => <option value={f.id} key={f.id}>{LEAGUE_INFO[f.league].name} · {name(f.a)} vs {name(f.b)}</option>)}</select></label><label className="field">두 번째 대진<select value={second} onChange={e => setSecond(e.target.value)}><option value="">대진 선택</option>{round.fixtures.filter(f => f.id !== first && f.league === firstFixture?.league).map(f => <option value={f.id} key={f.id}>{name(f.a)} vs {name(f.b)}</option>)}</select></label></div><button className="btn secondary" disabled={busy || !first || !second} onClick={async () => { if (await mutate('swapFixtures', { firstId: first, secondId: second })) { setFirst(''); setSecond(''); } }}>상대 교환</button></div>}</section>;
}
function Closing({ state, today, busy, mutate }: Props) {
  const season = currentSeason(state)!, round = season.rounds.find(r => !r.closed)!;
  const [orders, setOrders] = useState<Partial<Record<League, string[]>>>({}), [checked, setChecked] = useState<Partial<Record<League, boolean>>>({}), [confirm, setConfirm] = useState(false);
  const resultKey = state.matches.map(m => `${m.id}:${m.winner}:${m.voided}`).join(',');
  useEffect(() => { setOrders({}); setChecked({}); setConfirm(false); }, [round.id, resultKey]);
  const defaultPreview = movementPreview(state, round, season.exchanges);
  const explicit = Object.fromEntries(LEAGUES.filter(l => checked[l]).map(l => [l, orders[l] || defaultPreview.finalRows.filter(r => r.league === l).map(r => r.id)]));
  let preview = defaultPreview;
  try { preview = movementPreview(state, round, season.exchanges, explicit); } catch { /* Live results changed; the effect above clears obsolete ordering. */ }
  const complete = activeMatches(state, round.promotion.id).length === round.fixtures.length;
  const canClose = today >= round.promotion.start && (today > round.promotion.end || complete);
  const final = round.index === season.rounds.length;
  function move(l: League, ix: number, direction: number) {
    const ids = orders[l] || defaultPreview.finalRows.filter(r => r.league === l).map(r => r.id), copy = [...ids];
    [copy[ix], copy[ix + direction]] = [copy[ix + direction], copy[ix]];
    setOrders({ ...orders, [l]: copy }); setChecked({ ...checked, [l]: false }); setConfirm(false);
  }
  return <section className="panel closing-panel"><div className="section-head"><div><h3>{final ? '최종 순위·다음 시즌 리그 확정' : `${round.index}차 승강 미리보기·확정`}</h3><p className="muted">{final ? '이번 시즌 순위는 현재 리그에 남기고, 승강은 다음 시즌에 적용합니다.' : '확정하면 다음 구간으로 이동하고 RP와 연승 횟수는 0부터 시작합니다.'}</p></div></div>{!canClose && <div className="notice">승급 기간이 끝나거나 지정 경기를 모두 마치면 마감할 수 있습니다. 현재는 미리보기입니다.</div>}<div className="closing-leagues">{LEAGUES.map(l => { const group = defaultPreview.finalRows.filter(r => r.league === l), ordered = (orders[l] || group.map(r => r.id)).map(id => group.find(r => r.id === id)!); return <div key={l}><LeagueChip league={l} />{ordered.map((s, ix) => <div className="closing-row" key={s.id}><span>{ix + 1}</span><div><strong>{s.name}</strong><small>{s.rp} RP · {s.wins}승</small></div><span className={`movement ${preview.nextMembers[s.id] !== l ? 'changed' : ''}`}>{preview.nextMembers[s.id] === l ? '유지' : LEAGUE_INFO[preview.nextMembers[s.id]].name}</span><div className="order-buttons"><button className="icon-btn" aria-label={`${s.name} 동점 순서 올리기`} disabled={ix === 0 || compareScore(s, ordered[ix - 1]) !== 0} onClick={() => move(l, ix, -1)}><Icon name="up" size={15} /></button><button className="icon-btn" aria-label={`${s.name} 동점 순서 내리기`} disabled={ix === ordered.length - 1 || compareScore(s, ordered[ix + 1]) !== 0} onClick={() => move(l, ix, 1)}><Icon name="down" size={15} /></button></div></div>)}{defaultPreview.unresolved.includes(l) && <label className="check-field tie-confirm"><input type="checkbox" checked={!!checked[l]} onChange={e => { setChecked({ ...checked, [l]: e.target.checked }); setConfirm(false); }} />위 순서로 경계 동점을 확정합니다.</label>}</div>; })}</div><div className="placement-confirm"><label className="check-field"><input type="checkbox" checked={confirm} onChange={e => setConfirm(e.target.checked)} />순위·동점·승강 대상을 확인했습니다.</label><button className="btn primary" disabled={busy || !canClose || !confirm || !!preview.unresolved.length} onClick={() => mutate('close', { orders: explicit })}>{final ? '시즌 최종 마감' : '승강 확정·다음 구간으로'}<Icon name="check" size={18} /></button></div></section>;
}
function MatchManagement({ state, busy, mutate }: { state: Classroom; busy: boolean; mutate: Mutate }) {
  const [editing, setEditing] = useState(''), [winner, setWinner] = useState(''), [reason, setReason] = useState('');
  const name = (id: string) => state.students.find(s => s.id === id)?.name || '학생';
  const matches = state.matches.slice().reverse();
  return <section className="panel"><div className="section-head"><div><h2>경기 결과 확인·정정</h2><p className="muted">정정 이유를 남기면 점수·순위·남은 경기·연승 배지를 다시 계산합니다. 마감한 경기는 보존합니다.</p></div></div>{!matches.length ? <Empty icon="swords" title="아직 경기 기록이 없습니다">공용 화면에서 경기 결과를 입력해 주세요.</Empty> : <div className="match-management">{matches.map(m => { const closed = m.type === 'placement' ? state.placed : state.seasons.some(s => s.rounds.some(r => r.id === m.roundId && r.closed)); return <div className={`managed-match ${m.voided ? 'voided' : ''}`} key={m.id}><div className="managed-match-info"><span className="pill subtle">{m.type === 'placement' ? '배치전' : m.type === 'promotion' ? '승급 기간' : '리그전'}</span><strong>{name(m.a)} vs {name(m.b)}</strong><span>{m.voided ? '취소됨' : `${name(m.winner)} 승리`}</span><small>{timeLabel(m.at)} · {m.activity.name}</small>{m.revisions.length > 0 && <small>정정 {m.revisions.length}회 · {m.revisions.at(-1)!.reason}</small>}{!closed && !m.voided && <button className="text-btn" onClick={() => { setEditing(editing === m.id ? '' : m.id); setWinner(m.winner); setReason(''); }}>정정<Icon name="edit" size={15} /></button>}{closed && <span className="locked-label"><Icon name="lock" size={12} />마감</span>}</div>{editing === m.id && <div className="correction-form"><div className="form-grid two"><label className="field">승자<select value={winner} onChange={e => setWinner(e.target.value)}><option value={m.a}>{name(m.a)}</option><option value={m.b}>{name(m.b)}</option></select></label><label className="field">정정·취소 이유<input value={reason} onChange={e => setReason(e.target.value)} maxLength={150} placeholder="예: 승자를 반대로 입력함" /></label></div><div className="button-row"><button className="btn secondary small" disabled={busy || !reason.trim()} onClick={async () => { if (await mutate('correct', { id: m.id, winner, reason })) setEditing(''); }}>승자 정정</button><button className="btn danger small" disabled={busy || !reason.trim()} onClick={async () => { if (await mutate('correct', { id: m.id, voided: true, reason })) setEditing(''); }}>경기 취소·기회 복원</button></div></div>}</div>; })}</div>}</section>;
}
function Praise({ state, busy, mutate }: { state: Classroom; busy: boolean; mutate: Mutate }) {
  const [studentId, setStudentId] = useState(state.students[0]?.id || ''), [name, setName] = useState(''), [description, setDescription] = useState('');
  const [mode, setMode] = useState<'create' | 'award'>('create'), [templateId, setTemplateId] = useState('');
  const [color, setColor] = useState(DEFAULT_BADGE_COLOR);
  const colors = [{ name: '파랑', value: DEFAULT_BADGE_COLOR }, { name: '보라', value: '#8964b3' }, { name: '분홍', value: '#c66f91' }, { name: '초록', value: '#399779' }, { name: '주황', value: '#d47a43' }, { name: '금빛', value: '#bb9239' }];
  const templates = state.badgeTemplates || [];
  const selected = templates.find(t => t.id === templateId) || templates[0];
  const badges = state.badges.filter(b => b.kind === 'praise' && !b.revoked).slice().reverse();
  const alreadyAwarded = !!selected && badges.some(b => b.templateId === selected.id && b.studentId === studentId);
  async function create(e: FormEvent) { e.preventDefault(); if (await mutate('createBadgeTemplate', { name, description, color })) { setName(''); setDescription(''); } }
  async function award(e: FormEvent) { e.preventDefault(); if (selected) await mutate('praise', { studentId, templateId: selected.id }); }
  return <>
    <div className="tabs custom-honor-tabs" aria-label="커스텀 훈장 작업"><button className={mode === 'create' ? 'active' : ''} onClick={() => setMode('create')}>훈장 만들기</button><button className={mode === 'award' ? 'active' : ''} onClick={() => setMode('award')}>학생에게 수여</button></div>
    {mode === 'create' ? <div className="admin-two-columns">
      <form className="panel" onSubmit={create}>
        <span className="eyebrow">01 · 우리 반 훈장 준비</span><h2>커스텀 훈장 만들기</h2>
        <p className="muted">이름·색상·설명을 정해 저장해 두세요. 같은 훈장을 여러 학생에게 수여할 수 있습니다.</p>
        <div className="custom-honor-preview" style={{ backgroundColor: `${color}08`, borderColor: `${color}26` }}><MedalArt kind="praise" color={color} /><div><small>만들 훈장 미리보기</small><strong>{name.trim() || '새 커스텀 훈장'}</strong><p>{description.trim() || '훈장의 의미와 수여 기준을 정해 주세요.'}</p></div></div>
        <label className="field">훈장 이름<input value={name} onChange={e => setName(e.target.value)} placeholder="훈장 이름을 입력하세요" maxLength={30} required /></label>
        <div className="field"><span>훈장 색상</span><div className="honor-color-options" role="group" aria-label="훈장 색상">{colors.map(option => <button type="button" key={option.value} className={`honor-color-option ${color === option.value ? 'selected' : ''}`} aria-label={`${option.name} 훈장`} aria-pressed={color === option.value} onClick={() => setColor(option.value)}><span style={{ backgroundColor: option.value }}>{color === option.value && <Icon name="check" size={14} />}</span><small>{option.name}</small></button>)}</div><label className="honor-custom-color">직접 색상 선택<input type="color" aria-label="직접 훈장 색상 선택" value={color} onChange={e => setColor(e.target.value)} /><small>{color.toUpperCase()}</small></label></div>
        <label className="field">훈장 설명·수여 기준<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="어떤 모습에 수여할 훈장인가요?" rows={3} maxLength={150} required /></label>
        <button className="btn primary" disabled={busy || !name.trim() || !description.trim()}><Icon name="medal" size={18} />훈장 저장</button>
      </form>
      <section className="panel"><h2>미리 만든 훈장 <span className="muted">{templates.length}개</span></h2>{templates.length ? <div className="praise-list custom-honor-list">{templates.map(t => <div key={t.id}><MedalArt kind="praise" color={t.color} /><div><strong>{t.name}</strong><p>{t.description}</p></div><button className="text-btn" onClick={() => { setTemplateId(t.id); setMode('award'); }}>이 훈장 수여</button></div>)}</div> : <Empty icon="medal" title="우리 반 훈장을 준비해 주세요">저장한 훈장은 여기에서 다시 선택할 수 있습니다.</Empty>}</section>
    </div> : <div className="admin-two-columns">
      <form className="panel" onSubmit={award}>
        <span className="eyebrow">02 · 학생에게 수여</span><h2>만들어 둔 훈장 수여</h2>
        <p className="muted">훈장과 학생을 선택해 수여해 주세요.</p>
        {selected ? <>
          <label className="field">수여할 훈장<select value={selected.id} onChange={e => setTemplateId(e.target.value)}>{templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
          <div className="custom-honor-preview"><MedalArt kind="praise" color={selected.color} /><div><small>수여할 훈장</small><strong>{selected.name}</strong><p>{selected.description}</p></div></div>
          <label className="field">받을 학생<select value={studentId} onChange={e => setStudentId(e.target.value)}>{state.students.map(s => <option key={s.id} value={s.id}>{s.number}번 {s.name}</option>)}</select></label>
          {alreadyAwarded && <p className="notice mint">이 학생은 이미 이 훈장을 받았습니다.</p>}
          <button className="btn primary" disabled={busy || alreadyAwarded}><Icon name="star" size={18} />학생에게 훈장 수여</button>
        </> : <><Empty icon="medal" title="먼저 훈장을 만들어 주세요">훈장을 저장하면 학생에게 수여할 수 있습니다.</Empty><button type="button" className="btn secondary" onClick={() => setMode('create')}>훈장 만들기</button></>}
      </form>
      <section className="panel"><h2>수여한 커스텀 훈장</h2>{badges.length ? <div className="praise-list custom-honor-list">{badges.map(b => <div key={b.id}><MedalArt kind="praise" color={b.color} /><div><strong>{b.name}</strong><span>{state.students.find(s => s.id === b.studentId)?.name}</span><p>{b.description}</p></div><button className="text-btn" disabled={busy} onClick={() => mutate('revoke', { id: b.id })}>회수</button></div>)}</div> : <Empty icon="star" title="아직 수여한 훈장이 없습니다">수여한 훈장은 학생 카드에도 표시됩니다.</Empty>}</section>
    </div>}
  </>;
}
function Settings({ state, busy, mutate, disconnect }: Props) {
  const [name, setName] = useState(state.activity.name), [instructions, setInstructions] = useState(state.activity.instructions);
  return <div className="admin-two-columns"><form className="panel" onSubmit={e => { e.preventDefault(); mutate('activity', { name, instructions }); }}><h2>대결 활동 설정</h2><p className="muted">활동을 바꿔도 공통 승패 기록을 사용합니다. 기존 경기에는 당시 활동 안내가 남습니다.</p><label className="field">활동 이름<input value={name} onChange={e => setName(e.target.value)} required maxLength={50} /></label><label className="field">승자 판정·무승부 안내<textarea value={instructions} onChange={e => setInstructions(e.target.value)} required rows={5} maxLength={500} /></label><button className="btn primary" disabled={busy}>활동 설정 저장</button></form><div className="panel"><h2>데이터와 기기 관리</h2><p className="muted">경기 기록은 서버에 저장되어 연결된 태블릿이 함께 사용합니다.</p><div className="settings-actions"><a className="btn secondary" href="/api/export"><Icon name="download" size={18} />학급 기록 JSON 내려받기</a><button className="btn secondary" onClick={disconnect}><Icon name="lock" size={18} />이 기기 학급 연결 해제</button></div><p className="inline-hint">연결을 해제해도 학급과 경기 기록은 보존됩니다. 다시 사용할 때 교사 비밀번호로 연결해 주세요.</p></div></div>;
}
